version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.14-management
    ports:
      - "5672:5672"  # RabbitMQ default port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=maeve
      - RABBITMQ_DEFAULT_PASS=maeve
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mongo:
    container_name : maeve
    image: mongo
    volumes:
      - c:/data/db:/data/maevedb
      - c:/data/configdb:/data/maeveconfigdb
    ports:
      - '27017:27017'

volumes:
  rabbitmq_data:
